apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  HTTP_PORT: "80"
  MERGE_REQUEST_LABEL: {{ .Values.gitlab.mergeRequestLabel }}
  MESSAGE: {{ .Values.slack.message }}
  SLACK_AVATAR_URL: {{ .Values.slack.avatarUrl }}
  SLACK_USERNAME: {{ .Values.slack.username }}
  SLACK_WEBHOOK_URL: {{ .Values.slack.webhookUrl }}
